#ifndef SPOTTINGFBP
#define SPOTTINGFBP

#include "CellsFBP.h" 

// Include libraries
#include <stdio.h>
#include <string>
#include <vector>
#include <math.h>
#include <cmath>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <string>

// No need for using namespace if we will then use std:: everywhere
using namespace std;

// Also surely we should consider introducing some namespaces here instead of leaving
// everything in the global namespace. Seems like a recipe for disaster.

// Let's consider defining a strongly-typed struct for our
// spotting params
/**
 * The parameters that define the behaviour of the spotting function.
 */
struct SpottingParams {

	/**
	 * I wish I understood enough about fire and spotting to
	 * write the comment describing what this parameter is. From what I can
	 * see it's something like the angle of the window around the wind direction
	 * in which spotting can occur?
	 * 
	 * I think this is measured in degrees.
	 */
	double spot_angle;

	/**
	 * This is the probability of spotting at the center of the window. I kind of expected
	 * that there would be some kind of falloff in the spotting probability as we got
	 * farther from the center of the window, but this is not the case at all.
	 * Spotting probability is completely constant with respect to angle from
	 * what I can see in the code. Rather it seems to be a function of the distance.
	 * 
	 * I suppose the 0 in spot_0_prob really means that this is the probability of
	 * spotting at 0 distance (which is consistent with how it is used in the code).
	 */
	double spot_0_prob;

	/**
	 * This seems to be like the time it takes to spot or something. It is combined with
	 * the wind speed to influence the probability of spotting but I have a few questions.
	 *
	 * 1. If we increase the spotting time, the probability of spotting seems to decrease in the
	 *    codebase. This makes sense, as it seems to be increasing the expected time by decreasing the
	 *    likelihood of spotting, but this is a bit problematic when considering that currently,
	 *    if a cell does not send any messages in a time step, it is transitioned to a burned state.
	 *    As a result, if we increase the spotting time, the cell may just move to its burned state
	 *    before it has the chance to spot. Not an issue, just something worth considering. See the
	 *    comment on line 500 of CellsFBP.cpp for more discussion on this.
	 *
	 *    After further reflection (as is reflected in the long comment mentioned before),
	 *    I think this is probably fine, and I just wasn't understanding the mechanics
	 *    of cells burning out.
	 *
	 * 2. I guess I'm also curious what the 10 stands for. It would also be cool to know
	 *    if there are supposed to be units on the time.
	 */
	double spot_10_time;

	SpottingParams(
		double spot_angle,
		double spot_0_prob,
		double spot_10_time
	) : spot_angle(spot_angle), spot_0_prob(spot_0_prob), spot_10_time(spot_10_time) {}

};

// Some of these parameters are read-only and can totally be replaced with
// const-lvalue refs. While I am messing with the parameters, I might as well make them
// snake_case. The project doesn't really seem to have strong coding conventions,
// so I am using PascalCase for classes and snake_case for variables and functions.
//
// Also I think it's OK to leave this passing out the message list by value as
// elision will take care of it, but really it's probably best to pass in
// a reference to a message list that we can modify in place (since even with
// RVO, we will still have to extend our original message list in the calling frame
// with the new messages generated by this function into the return value list).
vector<int> SpottingFBP(
	// You can always add Boost and use boost::unordered_flat_map for some easy
	// ~15% unordered map performance improvements.
	const unordered_map<int, CellsFBP>& cells_obj, // Wish I knew more about these for better names.
	// Could be made flat and indexed with row * row_size + col for easy cache locality improvements
	// and corresponding performance gains.
	const vector<vector<int>>& coord_cells, // No clue what to call this.
	// boost::unordered_flat_set as above.
	const unordered_set<int> & avail_set, // The horse has been beat to death but I have no idea what this is.
	// Honestly, I'm pretty sure this is wind direction, but I have
	// no idea whether the one after this is actually wind speed.
	// If it is wind speed, I kind of think it's counted in raster cells
	// but I could be wildly off base on that. I also have no idea where to get it.
	// Right now I'm getting it from the input data frame when calling this from CellsFBP::manageFire,
	// but who knows whether that's right.
	double wind_direction, 
	double wind_speed, 
	const SpottingParams& spotting_params, 
	bool verbose);

#endif
