#ifndef SPOTTINGFBP
#define SPOTTINGFBP

// Include libraries
#include <stdio.h>
#include <string>
#include <vector>
#include <math.h>
#include <cmath>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <string>

#include "CellsFBP.h" 
#include "ReadArgs.h"

// No need for using namespace if we will then use std:: everywhere
using namespace std;

// Also surely we should consider introducing some namespaces here instead of leaving
// everything in the global namespace. Seems like a recipe for disaster.

// Some of these parameters are read-only and can totally be replaced with
// const-lvalue refs. While I am messing with the parameters, I might as well make them
// snake_case. The project doesn't really seem to have strong coding conventions,
// so I am using PascalCase for classes and snake_case for variables and functions.
//
// Also I think it's OK to leave this passing out the message list by value as
// elision will take care of it, but really it's probably best to pass in
// a reference to a message list that we can modify in place (since even with
// RVO, we will still have to extend our original message list in the calling frame
// with the new messages generated by this function into the return value list).
vector<int> SpottingFBP(
	// You can always add Boost and use boost::unordered_flat_map for some easy
	// ~15% unordered map performance improvements.
	const unordered_map<int, CellsFBP>& cells_obj, // Wish I knew more about these for better names.
	// Could be made flat and indexed with row * row_size + col for easy cache locality improvements
	// and corresponding performance gains.
	const vector<vector<int>>& coord_cells, // No clue what to call this.
	// boost::unordered_flat_set as above.
	const unordered_set<int> & avail_set, // The horse has been beat to death but I have no idea what this is.
	// Honestly, I'm pretty sure this is wind direction, but I have
	// no idea whether the one after this is actually wind speed.
	// If it is wind speed, I kind of think it's counted in raster cells
	// but I could be wildly off base on that. I also have no idea where to get it.
	// Right now I'm getting it from the input data frame when calling this from CellsFBP::manageFire,
	// but who knows whether that's right.
	double wind_direction, 
	double wind_speed, 
	const SpottingParams& spotting_params, 
	bool verbose);

#endif
